import type { AppState } from './types';

export const DEFAULT_APP_STATE: AppState = {
  siteContent: {
    hero: {
      title: 'מלכתא: טעמים של בית',
      subtitle: 'אוכל ביתי אותנטי, מוכן באהבה כל יום מחדש.',
      image: 'https://placehold.co/1920x1080',
    },
    about: {
      short: 'בלב העיר, שוכנת "מלכתא", מסעדה שהיא בית. אנו מגישים באהבה את מיטב המאכלים מהמטבח הביתי, עם חומרי גלם טריים ומתכונים שעוברים מדור לדור.',
      long: 'סיפורה של "מלכתא" מתחיל במטבח של סבתא, שם התבשל הקסם. כל מנה שלנו היא מסע בזמן, חזרה לטעמים של פעם, לארוחות שישי ולחגים. אנו מאמינים שאוכל הוא יותר מסתם מזון - הוא זיכרון, הוא חוויה, והוא חיבור. לכן, אנו מקפידים על כל פרט, מהירקות הטריים שאנחנו בוחרים בבוקר ועד לבישול האיטי והסבלני שמוציא את המיטב מכל תבשיל. בואו לחוות איתנו את טעם הבית.',
      image: 'https://placehold.co/600x400',
    },
    contact: {
      address: 'רחוב הנביאים 1, תל אביב',
      phone: '03-1234567',
      whatsapp: '972501234567',
      email: 'contact@malkata.co.il',
      hours: 'א׳-ה׳: 11:00 - 22:00 | ו׳: 09:00 - 15:00',
    },
    menu: {
      mainImage: 'https://placehold.co/1600x400',
    }
  },
  categories: [
    { id: '1', name: 'עיקריות', slug: 'main-dishes', description: 'הלב של הארוחה, מנות עשירות ומנחמות.', image: 'https://placehold.co/1200x400' },
    { id: '2', name: 'תוספות', slug: 'side-dishes', description: 'מה שהופך ארוחה טובה למצוינת.', image: 'https://placehold.co/1200x400' },
    { id: '3', name: 'סלטים', slug: 'salads', description: 'רעננות וצבעוניות בכל ביס.', image: 'https://placehold.co/1200x400' },
  ],
  dishes: [
    {
      id: 'd1',
      name: 'קציצות ברוטב עגבניות',
      shortDescription: 'קציצות בקר עסיסיות ברוטב עגבניות ביתי.',
      fullDescription: 'קציצות בקר נימוחות ומלאות טעם, שוחות ברוטב עגבניות עשיר שהתבשל שעות ארוכות עם עשבי תיבול טריים. מוגש על מצע של אורז לבן.',
      price: 58,
      images: ['https://placehold.co/600x400', 'https://placehold.co/600x400'],
      categoryId: '1',
      isAvailable: true,
      tags: [],
    },
    {
      id: 'd2',
      name: 'אורז לבן אחד אחד',
      shortDescription: 'אורז בסמטי רך ומושלם.',
      fullDescription: 'גרגירים של אורז בסמטי איכותי, מבושלים בדיוק במידה הנכונה לקבלת מרקם אוורירי וטעם עדין שמשתלב נהדר עם כל מנה עיקרית.',
      price: 15,
      images: ['https://placehold.co/600x400'],
      categoryId: '2',
      isAvailable: true,
      tags: [],
    },
    {
      id: 'd3',
      name: 'סלט ירקות קצוץ',
      shortDescription: 'מלפפון, עגבנייה, בצל ופטרוזיליה קצוצים דק.',
      fullDescription: 'סלט ישראלי קלאסי, טרי ומרענן. ירקות פריכים קצוצים דק דק ומתובלים בשמן זית כתית, לימון סחוט טרי ומעט מלח.',
      price: 25,
      images: ['https://placehold.co/600x400'],
      categoryId: '3',
      isAvailable: true,
      tags: ['vegan'],
    },
    {
      id: 'd4',
      name: 'שקשוקה חריפה',
      shortDescription: 'תבשיל עגבניות ופלפלים עם ביצים.',
      fullDescription: 'שקשוקה אדומה ולוהטת עם רוטב עגבניות, פלפלים, שום והרבה פפריקה חריפה. שתי ביצי עין רכות מעל, מושלם לניגוב עם חלה טרייה.',
      price: 45,
      images: ['https://placehold.co/600x400'],
      categoryId: '1',
      isAvailable: true,
      tags: ['spicy'],
    },
    {
      id: 'd5',
      name: 'קוסקוס עם ירקות',
      shortDescription: 'סולת רכה עם מרק ירקות עשיר.',
      fullDescription: 'קוסקוס ביתי אמיתי, רך ואוורירי, מוגש עם מרק ירקות כתום ועשיר, מלא בקישואים, גזר, דלעת וגרגירי חומוס. מנה שהיא ארוחה שלמה.',
      price: 62,
      images: ['https://placehold.co/600x400'],
      categoryId: '1',
      isAvailable: true,
      tags: ['vegan'],
    },
  ],
  testimonials: [
    { id: 't1', name: 'יוסי כהן', quote: 'הרגשתי כאילו חזרתי למטבח של אמא. כל ביס היה תענוג!' },
    { id: 't2', name: 'שרה לוי', quote: 'הזמנתי קייטרינג לאירוע והכל היה פשוט מושלם. האורחים לא הפסיקו להחמיא.' },
    { id: 't3', name: 'דנה ישראלי', quote: 'הקציצות שלהם זה משהו שלא טועמים כל יום. ממכר!' },
  ],
  gallery: [
    { id: 'g1', src: 'https://placehold.co/600x400', alt: 'תמונת אווירה במסעדה' },
    { id: 'g2', src: 'https://placehold.co/600x400', alt: 'מנה מעוררת תיאבון' },
    { id: 'g3', src: 'https://placehold.co/600x400', alt: 'תהליך הבישול במטבח' },
    { id: 'g4', src: 'https://placehold.co/600x400', alt: 'צוות המסעדה' },
    { id: 'g5', src: 'https://placehold.co/600x400', alt: 'פינת ישיבה נעימה' },
    { id: 'g6', src: 'https://placehold.co/600x400', alt: 'קינוח מפנק' },
  ],
  design: {
    theme: 'default',
    animation: 'fadeIn',
  },
};
